/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StatusRouteImport } from './routes/status'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/library'
    | '/login'
    | '/projects'
    | '/register'
    | '/status'
    | '/templates'
    | '/books/$bookId'
    | '/projects/$projectId'
    | '/templates/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/library'
    | '/login'
    | '/projects'
    | '/register'
    | '/status'
    | '/templates'
    | '/books/$bookId'
    | '/projects/$projectId'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/library'
    | '/login'
    | '/projects'
    | '/register'
    | '/status'
    | '/templates'
    | '/books/$bookId'
    | '/projects/$projectId'
    | '/templates/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StatusRoute: typeof StatusRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  BooksBookIdRoute: typeof BooksBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StatusRoute: StatusRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  BooksBookIdRoute: BooksBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
